apiVersion: v1
appVersion: 0.0.48
description: A Helm chart for the JenkinsX sonar-scanner app
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/go.png
name: jx-app-sonar-scanner
version: 0.0.48
