# Default values for Go projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: gcr.io/jx-mar19/jx-app-sonar-scanner
  tag: 0.0.41
sqServer: "{{ .Values.sqServer }}"
apiKey: "{{ .Values.apiKey }}"
scanonpreview: "{{ .Values.scanonpreview }}"
scanonrelease: "{{ .Values.scanonrelease }}"
